export const IS_FETCHING_GALLERY: string = "IS_FETCHING_GALLERY"
export const IS_FETCHING_GALLERY_COMPLETED: string = "IS_FETCHING_GALLERY_COMPLETED"
export const IS_FETCHING_GALLERY_FAILED: string = "IS_FETCHING_GALLERY_FAILED"

export const IS_FETCHING_COMMENTS: string = "IS_FETCHING_COMMENTS"
export const IS_FETCHING_COMMENTS_COMPLETED: string = "IS_FETCHING_COMMENTS_COMPLETED"
export const IS_FETCHING_COMMENTS_FAILED: string = "IS_FETCHING_COMMENTS_FAILED"